### ISSUE TITLE
Got crash when right click on other's profile to control the volumes

### ISSUE THREAD

**Issue by Silentstorm57** [Zerthox/BetterDiscord-Plugins#140] opened 2023-02-28 04:00 UTC
### Bug description

I Just got reinstall the all of the discord and Betterdiscord to fix the crash of enter to the settings on discord. somehow other crash has been solved but this plugin has got same crash page when I was control the volume for the others. if disable this plugin, discord has been stable and no more crashes.

### Plugin

BetterVolume

### Plugin version

2.3.2 rc1

### Discord client

Stable

**Comment by audimatic** [comment] 2023-02-28 10:21
cuz of new discord update

**Comment by Gamerx007** [comment] 2023-03-01 01:33
yep I have the same issue and I can also confirm that BetterVolume is the cause of the crashes sadly

good luck with the update and thank you <3

**Comment by Zzeyy** [comment] 2023-03-01 11:36
I confirm this

**Comment by Zerthox** [comment] 2023-03-01 13:46
This is caused by context menu components exposed by BetterDiscord's API missing. The plugin should work again once BD releases a fix.

**Comment by Zerthox** [comment] 2023-03-02 21:58
Fixed with BD 1.8.5.

**Closed by Zerthox** 2023-03-02 21:58 UTC
Labels: bug, discord update
