### ISSUE TITLE
BetterVolume crashes Discord when right clicking an user

### ISSUE THREAD

**Issue by ElTioRata** [Zerthox/BetterDiscord-Plugins#148] opened 2023-04-05 00:36 UTC
### Bug description

The title says it all.

### Plugin

BetterVolume

### Plugin version

v2.4.0

### Discord client

Stable

**Comment by Zerthox** [comment] 2023-04-05 09:41
Duplicate of #147

**Closed** 2023-04-05 09:42 UTC
Labels: duplicate
