### ISSUE TITLE
Better volume resets to - value

### ISSUE THREAD

**Issue by Possuz** [Zerthox/BetterDiscord-Plugins#183] opened 2024-08-09 20:03 UTC
### Bug description

is there some way to fix this when i set volöume over 200% it resets to - values

### Plugin

better volume

### Plugin version

v1.5.0

### Discord client

Stable

**Comment by azalty** [comment] 2024-08-09 20:43
duplicate of #151 #177

**Closed** 2024-08-09 23:08 UTC
Labels: bug, duplicate
