### ISSUE TITLE
Better volume not working at all

### ISSUE THREAD

**Issue by jcliu0** [Zerthox/BetterDiscord-Plugins#159] opened 2023-08-13 04:12 UTC
### Bug description

I cannot get it to do what it used to do, i cannot change volume above 200% with or without the experimental option ticked or not

### Plugin

BetterVolume

### Plugin version

latest

### Discord client

Stable

**Comment by Zerthox** [comment] 2023-08-13 17:14
Duplicate of #151.

**Closed by Zerthox** 2023-08-13 17:14 UTC
Labels: duplicate
