### ISSUE TITLE
[BUG] Better Folders & Better Volume can´t be constructed/loaded

### ISSUE THREAD

**Issue by BlueStarBRS** [Zerthox/BetterDiscord-Plugins#99] opened 2022-01-31 16:29 UTC
since the weekend it´s stopped working 
the stuff don´t want be loaded and cant be constructed 

more details:
![image](https://user-images.githubusercontent.com/25110093/151832408-1eb7afc9-0c5a-4c28-8ef0-9893a42fd914.png)
![image](https://user-images.githubusercontent.com/25110093/151832418-f25f71f4-fe0d-4aa3-b62d-f2573b0ee7a0.png)

**Comment by Zerthox** [comment] 2022-01-31 19:13
Duplicate of #90. Has already been fixed with the most recent update, you can wait until it is approved for the BetterDiscord site or download it directly from the repo.

**Comment by Zerthox** [comment] 2022-02-04 23:30
Please read the comment above. It has already been fixed. The update for the BetterDiscord site has also been approved a few hours ago. So finally closing this.

**Closed by Zerthox** 2022-02-04 23:30 UTC
Labels: bug, duplicate, discord update
