### ISSUE TITLE
[BUG] Better Volume Plugin canot be constructed

### ISSUE THREAD

**Issue by MysteryTopHat** [Zerthox/BetterDiscord-Plugins#97] opened 2022-01-31 15:58 UTC
I opened up discord and got this error message for the plugin. 
``
Better volume 
BetterVolume: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:311255)
    at Object.loadAddon (<anonymous>:4:273400)
    at Object.loadAddon (<anonymous>:4:310367)
    at Object.loadAllAddons (<anonymous>:4:275654)
    at Object.initialize (<anonymous>:4:270142)
    at Object.initialize (<anonymous>:4:309577)
    at Object.startup (<anonymous>:4:373389)
    `` 
I am using Manjaro Linux GNOME and using the normal release of discord, if that helps.

**Comment by Zerthox** [comment] 2022-01-31 19:12
Duplicate of #90. Has already been fixed with the most recent update, you can wait until it is approved for the BetterDiscord site or download it directly from the repo.

**Closed by Zerthox** 2022-01-31 19:12 UTC
Labels: bug, duplicate, discord update
