### ISSUE TITLE
BetterFolders - Blank Window

### ISSUE THREAD

**Issue by KingGamingYT** [Zerthox/BetterDiscord-Plugins#130] opened 2022-11-22 00:44 UTC
Upon installation and enabling BetterFolders, after a discord restart the program will show the UI for a fraction of a second, and then the window will turn blank and stay blank.
![image](https://user-images.githubusercontent.com/45918062/203186927-ae219cc4-dab0-47fd-a534-dc5e02900411.png)

**Comment by Zerthox** [comment] 2022-11-22 13:15
I'm unable to reproduce. Are you on stable Discord? Are you on the most recent version of BetterFolders (3.3.0)? Could you check the console for output/errors? Usually in the console you should see:
![image](https://user-images.githubusercontent.com/19844016/203323053-073a9693-768b-4577-b7c9-6e861695bc2d.png)

**Comment by KingGamingYT** [comment] 2022-11-22 20:29
This is what I could see in the console when the problem is occurring. I was on the most recent version of the plugin, and I'm using Discord's Stable branch.
![image](https://user-images.githubusercontent.com/45918062/203414685-1429444a-7696-4aa6-b5e0-75979d85537b.png)

**Comment by Zerthox** [comment] 2022-11-22 20:46
Hmm looks like the first half is working correctly, but it doesnt perform the nested patch. What about errors in the console? Could you try removing all other plugins to rule out incompatibility issues?

**Comment by KingGamingYT** [comment] 2022-11-23 22:56
Discord starts fine without any other plugins besides BetterFolders. I will bit by bit move my plugins back in and see which one is causing the confliction.

**Comment by KingGamingYT** [comment] 2022-11-23 23:22
Alright, so this is kinda funny, it's OnlineFriendCount that is causing the issue, so something in that plugin is causing conflicts in this one.

**Comment by Zerthox** [comment] 2022-11-25 16:26
I identified the issue. The bug in the code existed for longer than the recent fix, but apparently did not get triggered or wasn't reported. It's also possible Discord changed something that affects rendering in some way and triggers the bug as a result.

It should be fixed with the latest versions of BetterFolders and OnlineFriendCount.

**Closed by Zerthox** 2022-11-25 16:26 UTC
Labels: bug

**Comment by RobinRMC** [comment] 2022-11-26 19:26
The fix for OnlineFriendCount was not successful. Please reopen.

**Comment by Zerthox** [comment] 2022-11-26 22:57
The bug described in this issue only occured when both BetterFolders and OnlineFriendCount were enabled. If you want to report a bug regarding OnlineFriendCount, please open a new issue.
