### ISSUE TITLE
BetterVolume not loading on BD. 

### ISSUE THREAD

**Issue by SquirrelKiev** [Zerthox/BetterDiscord-Plugins#93] opened 2022-01-29 23:01 UTC
Log provided by BD: 
```
BetterVolume: Could not be constructed.
at Object.initializeAddon (<anonymous>:4:311255)
at Object.loadAddon (<anonymous>:4:273400)
at Object.loadAddon (<anonymous>:4:310367)
at FSWatcher.<anonymous> (<anonymous>:4:271259)
```

**Comment by Zerthox** [comment] 2022-01-30 00:35
Duplicate of #90.

**Closed by Zerthox** 2022-01-30 00:35 UTC
Labels: bug, duplicate, discord update
