### ISSUE TITLE
[BUG] Online Friends Count Cannot Be Constructed

### ISSUE THREAD

**Issue by MysteryTopHat** [Zerthox/BetterDiscord-Plugins#98] opened 2022-01-31 16:02 UTC
Here is the error output upon launch 
``
OnlineFriendCount: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:311255)
    at Object.loadAddon (<anonymous>:4:273400)
    at Object.loadAddon (<anonymous>:4:310367)
    at Object.reloadAddon (<anonymous>:4:274105)
    at FSWatcher.<anonymous> (<anonymous>:4:271293)
``
This is on Manjaro GNOME and with the regular release of discord.

**Comment by Zerthox** [comment] 2022-01-31 19:12
Duplicate of #90. Has already been fixed with the most recent update, you can wait until it is approved for the BetterDiscord site or download it directly from the repo.

**Closed by Zerthox** 2022-01-31 19:12 UTC
Labels: bug, duplicate, discord update
