### ISSUE TITLE
Doesent work anymore

### ISSUE THREAD

**Issue by turtle3188** [Zerthox/BetterDiscord-Plugins#169] opened 2023-11-04 00:32 UTC
### Bug description

legit doesent work anymore and havent for a long time plz fix

### Plugin

BetterVolume

### Plugin version

V.2.5.0

### Discord client

Stable

**Comment by Zerthox** [comment] 2023-11-04 12:26
Unable to reproduce any problems with the plugin on Discord stable. What is the issue(s) you are running into? Do you have any other plugins that might be interfering?

**Comment by mogsor** [comment] 2023-11-05 19:08
Hey I'm also having issues. I can use the scroll wheel and set values manually, but if I raise the volume above 200 it doesn't actually increase the volume, and when I reopen the context menu it resets to 200.

This is on Discord Stable on Linux. I don't have any other plugins that look like they'd affect the volume. Currently it's:

- BetterVolume
- BDFDB
- InsertTimestamps
- KeywordTracker
- NoReplyMention
- PluginRepo
- RemoveChatButtons
- YABDP4Nitro
- ZeresPluginLibrary

**Comment by Zerthox** [comment] 2023-11-06 22:29
That's Discord's audio settings experiment interfering, which is a known issue. See #151.

But I don't know if @turtle3188 is referring to the same problem. "Doesn't work anymore" contains basically no relevant information and as a result I will be closing this. Feel free to reopen or submit another useful bug report.

**Closed by Zerthox** 2023-11-06 22:29 UTC
Labels: bug
