### ISSUE TITLE
BetterVolume could not be constructed

### ISSUE THREAD

**Issue by KeryWT** [Zerthox/BetterDiscord-Plugins#92] opened 2022-01-29 13:10 UTC
![image](https://user-images.githubusercontent.com/53485931/151662235-1030ca45-4ed1-40bd-be24-e70a43b79f33.png)

This happens when I open discord, and it tries to start the plugin.

> BetterVolume: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:311255)
    at Object.loadAddon (<anonymous>:4:273400)
    at Object.loadAddon (<anonymous>:4:310367)
    at FSWatcher.<anonymous> (<anonymous>:4:271259)

**Comment by GEORGEREP** [comment] 2022-01-29 16:31
Same for me
![Screenshot_1](https://user-images.githubusercontent.com/95755065/151668959-1f4d44f5-a530-4dc5-9f58-ab16de873ecb.png)

**Comment by Zerthox** [comment] 2022-01-29 18:11
Duplicate of #90.

**Closed by Zerthox** 2022-01-29 18:11 UTC
Labels: bug, duplicate, discord update
